const pumps = [
  {
    id: 'p001',
    name: 'Centrifugal Pump CP-450',
    manufacturer: 'Grundfos India',
    type: 'centrifugal',
    flowRate: 450,
    head: 120,
    efficiency: 87,
    power: 15,
    price: 125000,
    esgRating: 'A+',
    energyRating: '5-star',
    material: 'stainless-steel',
    certification: ['bis', 'ce'],
    deliveryTime: 7,
    image: 'https://via.placeholder.com/150',
    description: 'High-efficiency centrifugal pump ideal for industrial applications with excellent energy savings.'
  },
  {
    id: 'p002',
    name: 'Submersible Pump SP-200',
    manufacturer: 'Kirloskar Brothers',
    type: 'submersible',
    flowRate: 200,
    head: 80,
    efficiency: 82,
    power: 7.5,
    price: 85000,
    esgRating: 'A',
    energyRating: '4-star',
    material: 'cast-iron',
    certification: ['bis', 'isi'],
    deliveryTime: 5,
    image: 'https://via.placeholder.com/150',
    description: 'Reliable submersible pump for water supply and irrigation applications.'
  },
  {
    id: 'p003',
    name: 'Multistage Pump MS-350',
    manufacturer: 'KSB Pumps',
    type: 'multistage',
    flowRate: 350,
    head: 200,
    efficiency: 89,
    power: 22,
    price: 175000,
    esgRating: 'A+',
    energyRating: '5-star',
    material: 'stainless-steel',
    certification: ['bis', 'ce', 'api'],
    deliveryTime: 10,
    image: 'https://via.placeholder.com/150',
    description: 'High-pressure multistage pump for industrial and municipal applications.'
  },
  {
    id: 'p004',
    name: 'Self-Priming Pump SPP-150',
    manufacturer: 'CRI Pumps',
    type: 'self-priming',
    flowRate: 150,
    head: 60,
    efficiency: 78,
    power: 5.5,
    price: 65000,
    esgRating: 'B+',
    energyRating: '3-star',
    material: 'cast-iron',
    certification: ['isi'],
    deliveryTime: 3,
    image: 'https://via.placeholder.com/150',
    description: 'Self-priming pump for agricultural and domestic water supply applications.'
  },
  {
    id: 'p005',
    name: 'Magnetic Drive Pump MD-100',
    manufacturer: 'Flowserve India',
    type: 'magnetic-drive',
    flowRate: 100,
    head: 40,
    efficiency: 75,
    power: 3,
    price: 95000,
    esgRating: 'A',
    energyRating: '4-star',
    material: 'plastic',
    certification: ['ce', 'atex'],
    deliveryTime: 14,
    image: 'https://via.placeholder.com/150',
    description: 'Leak-free magnetic drive pump for chemical processing applications.'
  },
  {
    id: 'p006',
    name: 'Vertical Turbine Pump VT-500',
    manufacturer: 'Kirloskar Brothers',
    type: 'vertical-turbine',
    flowRate: 500,
    head: 150,
    efficiency: 84,
    power: 30,
    price: 220000,
    esgRating: 'A',
    energyRating: '4-star',
    material: 'stainless-steel',
    certification: ['bis', 'api'],
    deliveryTime: 21,
    image: 'https://via.placeholder.com/150',
    description: 'High-capacity vertical turbine pump for water supply and irrigation projects.'
  },
  {
    id: 'p007',
    name: 'Peristaltic Pump PP-50',
    manufacturer: 'Watson-Marlow',
    type: 'peristaltic',
    flowRate: 50,
    head: 25,
    efficiency: 70,
    power: 1.5,
    price: 110000,
    esgRating: 'A+',
    energyRating: '5-star',
    material: 'plastic',
    certification: ['ce', '3a'],
    deliveryTime: 7,
    image: 'https://via.placeholder.com/150',
    description: 'Precise peristaltic pump for pharmaceutical and food processing applications.'
  },
  {
    id: 'p008',
    name: 'Positive Displacement Pump PD-75',
    manufacturer: 'Rotodel',
    type: 'positive-displacement',
    flowRate: 75,
    head: 90,
    efficiency: 80,
    power: 5.5,
    price: 135000,
    esgRating: 'B+',
    energyRating: '3-star',
    material: 'cast-iron',
    certification: ['bis'],
    deliveryTime: 10,
    image: 'https://via.placeholder.com/150',
    description: 'Robust positive displacement pump for viscous fluid handling applications.'
  }
];

export default pumps;