const oems = [
  {
    id: 'oem001',
    name: 'Grundfos India',
    logo: 'https://via.placeholder.com/150',
    location: 'Chennai, Tamil Nadu',
    established: 1998,
    esgRating: 'A+',
    specialties: ['centrifugal', 'submersible', 'multistage'],
    marketShare: 22,
    description: 'Leading manufacturer of high-quality pumps with focus on energy efficiency and sustainability.',
    newReleases: 3,
    serviceNetwork: 120,
    certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001'],
    website: 'https://www.grundfos.com/in'
  },
  {
    id: 'oem002',
    name: 'Kirloskar Brothers',
    logo: 'https://via.placeholder.com/150',
    location: 'Pune, Maharashtra',
    established: 1888,
    esgRating: 'A',
    specialties: ['centrifugal', 'submersible', 'vertical-turbine'],
    marketShare: 18,
    description: 'One of India\'s oldest pump manufacturers with a wide range of industrial and agricultural pumps.',
    newReleases: 2,
    serviceNetwork: 200,
    certifications: ['ISO 9001', 'ISO 14001', 'ISO 50001'],
    website: 'https://www.kirloskarpumps.com'
  },
  {
    id: 'oem003',
    name: 'KSB Pumps',
    logo: 'https://via.placeholder.com/150',
    location: 'Mumbai, Maharashtra',
    established: 1960,
    esgRating: 'A+',
    specialties: ['centrifugal', 'multistage', 'self-priming'],
    marketShare: 15,
    description: 'German engineering with Indian manufacturing excellence, specializing in high-performance pumps.',
    newReleases: 4,
    serviceNetwork: 85,
    certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001'],
    website: 'https://www.ksb.com/en-in'
  },
  {
    id: 'oem004',
    name: 'CRI Pumps',
    logo: 'https://via.placeholder.com/150',
    location: 'Coimbatore, Tamil Nadu',
    established: 1961,
    esgRating: 'B+',
    specialties: ['submersible', 'self-priming', 'centrifugal'],
    marketShare: 12,
    description: 'Manufacturer of energy-efficient pumps for agricultural and domestic applications.',
    newReleases: 1,
    serviceNetwork: 150,
    certifications: ['ISO 9001', 'BEE Star Rating'],
    website: 'https://www.crigroups.com'
  },
  {
    id: 'oem005',
    name: 'Flowserve India',
    logo: 'https://via.placeholder.com/150',
    location: 'Chennai, Tamil Nadu',
    established: 1995,
    esgRating: 'A',
    specialties: ['centrifugal', 'magnetic-drive', 'positive-displacement'],
    marketShare: 10,
    description: 'Global leader in fluid motion control with advanced pump technologies for critical applications.',
    newReleases: 2,
    serviceNetwork: 60,
    certifications: ['ISO 9001', 'ISO 14001', 'API 610'],
    website: 'https://www.flowserve.com'
  },
  {
    id: 'oem006',
    name: 'Shakti Pumps',
    logo: 'https://via.placeholder.com/150',
    location: 'Indore, Madhya Pradesh',
    established: 1982,
    esgRating: 'B+',
    specialties: ['submersible', 'solar', 'centrifugal'],
    marketShare: 8,
    description: 'Pioneer in solar pumping solutions with focus on sustainable water management.',
    newReleases: 3,
    serviceNetwork: 100,
    certifications: ['ISO 9001', 'BEE Star Rating'],
    website: 'https://www.shaktipumps.com'
  },
  {
    id: 'oem007',
    name: 'Wilo Mather and Platt',
    logo: 'https://via.placeholder.com/150',
    location: 'Pune, Maharashtra',
    established: 2005,
    esgRating: 'A',
    specialties: ['centrifugal', 'multistage', 'vertical-turbine'],
    marketShare: 7,
    description: 'Indo-German joint venture specializing in high-efficiency pumps for building services and industry.',
    newReleases: 2,
    serviceNetwork: 45,
    certifications: ['ISO 9001', 'ISO 14001', 'ISO 50001'],
    website: 'https://wilo.com/in/en'
  },
  {
    id: 'oem008',
    name: 'WPIL Limited',
    logo: 'https://via.placeholder.com/150',
    location: 'Kolkata, West Bengal',
    established: 1952,
    esgRating: 'B',
    specialties: ['centrifugal', 'vertical-turbine', 'positive-displacement'],
    marketShare: 5,
    description: 'Specialized in large pumps for water infrastructure, power, and industrial applications.',
    newReleases: 1,
    serviceNetwork: 30,
    certifications: ['ISO 9001', 'ISO 14001'],
    website: 'https://www.wpil.co.in'
  }
];

export default oems;